spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/elearning
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: file:src/main/resources/static/





